default: &default
  adapter: mysql
  # adapter: jdbcmysql
  # driver: com.mysql.cj.jdbc.Driver
  username: siddeshwar
  password: sM62Ahm5>J:+<9}D-y"d#u
  # url: jdbc:mysql://localhost:3306/rails_demo
  database: rails_demo

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
